name: filmdevelopmentcompanion
description: An application to check the status of film development orders

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0+4
  intl: ^0.16.1
  sqflite: ^1.3.0
  path: ^1.6.4
  google_fonts: ^0.3.10
  html: ^0.14.0+3
  jiffy: ^3.0.1
  flutter:
    sdk: flutter
  provider: ^4.0.4
  flutter_launcher_icons: ^0.7.4
  cupertino_icons: ^0.1.2
  expandable: ^4.1.3

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/appicon.png"
  image_path_android: "assets/appicon.png"
  adaptive_icon_background: "#ff6e40"
  adaptive_icon_foreground: "assets/foreground.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  icapps_license: ^0.0.6

flutter:
  fonts:
    - family: Futura
      fonts:
        - asset: fonts/Futura-Book.ttf

  uses-material-design: true
