name: filmdevelopmentcompanion
description: An application to check the status of film development orders at drugstores

version: 1.0.4+6

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  shared_preferences: ^0.5.8
  http: ^0.12.1
  sqflite: ^1.3.1
  path: ^1.6.4
  html: ^0.14.0+3
  jiffy: ^3.0.1
  flutter:
    sdk: flutter
  provider: ^4.3.1
  path_provider: ^1.6.11
  flutter_launcher_icons: ^0.7.4
  cupertino_icons: ^0.1.2
  expandable: ^4.1.3
  flutter_localizations:
    sdk: flutter

# Run this command when changing icons
#flutter pub run flutter_launcher_icons:main
flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/appicon.png"
  image_path_android: "assets/appicon.png"
  adaptive_icon_background: "#f25757"
  adaptive_icon_foreground: "assets/foreground.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  icapps_license: ^0.0.6

flutter:
  fonts:
    - family: Futura
      fonts:
        - asset: fonts/Futura-Book.ttf
  assets:
    - "assets/RossmannExample.png"
    - "assets/dmExample.png"
    - "i18n/en.json"
    - "i18n/de.json"

  uses-material-design: true
